spring.application.name=backend

#db_connection

spring.datasource.url=jdbc:postgresql://localhost:5500/db_LMS
spring.datasource.username=postgres
spring.datasource.password=Yuva15
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#default login credits in testing

spring.security.user.name=user
spring.security.user.password=0000